version: "3.4"

services:
  darts_score_ui:
    image: kosterra/darts-score-ui:latest
    container_name: darts_score_ui
    restart: always
    ports:
      - 4000:80
    env_file:
      - ./ui.env

  darts_score_api:
    image: kosterra/darts-score-api:latest
    container_name: darts_score_api
    restart: always
    ports:
      - 4001:3001
    env_file:
      - ./api.env
    volumes:
      - type: volume
        source: darts_score_data
        target: /app/data

  mongo:
    image: mongo
    container_name: darts_score_mongo
    restart: always
    env_file:
      - ./mongo.env
    volumes:
      - type: volume
        source: darts_score_db
        target: /data/db

volumes:
  darts_score_data:
    name: darts_score_data
  darts_score_db:
    name: darts_score_db

